### PR TITLE
Add W3C

### PR DESCRIPTION
**Pull request by darobin**
This adds the primary projects for W3C, and W3C as an overall collection.

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Thanks for your PR @darobin!
In order to merge your PR, you need to remove the hyphen from the filename `w3c-tag.yaml`. It should be saved as `w3ctag.yaml`, ie, the same as the slug name.
Then everything should be good to go.

**Comment by darobin** [comment]
Ah, sorry, I hadn't seen that that was required. Should be good now, thanks!

**Comment by ryscheng** [comment]
@darobin I'm so sorry, we did a schema change since this PR was submitted

slug => name
name => display_name

Hopefully this isn't too annoying for you to change real quick

**Review by ccerv1 — APPROVED** [review]
I've made the changes to reflect the new schema directly 😉 
Should be good to go now. Thank you!!!

**Pull request merged**
