### PR TITLE
Add NOGS

### PR DESCRIPTION
**Pull request by apbigcod**

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
gm gm!
please have a look at the changes i made to your project file. in general, we recommend projects user their github org rather than a specific repo to instantiate their project. (probably 90% of projects choose this option). in your case, this will also indicate a longer track record of building. 

**let me know if you are OK with this change**. if so, i will proceed to validate the addresses (they look fine a glance). if not, feel free to modify the project file again but ensure the name follows [our naming convention](https://docs.opensource.observer/docs/contribute/project-data#2-locate-or-create-a-new-project-file) to prevent any ambiguity

cheers!

**Comment by apbigcod** [comment]
That's perfect, thanks for the updates. Happy to move forward

**Comment by ryscheng** [comment]
@apbigcod this is tricky. But make sure to use `.yaml` file extensions, otherwise automated validation will fail.

I'll add a better error message

**Review by ccerv1 — APPROVED** [review]

**Comment by ccerv1** [comment]
@apbigcod thanks! you're PR is merged and good to go now

**Pull request merged**
