### PR TITLE
Added npm links and github repos for EVM Explorer and Dspyt DAO

### PR DESCRIPTION
**Pull request by Pfed-prog**

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]

**Review by ccerv1 — APPROVED** [review]
looks fine

**Review by ccerv1 — CHANGES_REQUESTED** [review]
You need to determine which project file will own the packages. It can't be both. Getting this error:

```
AssertionError: Duplicates found: {
  "https://www.npmjs.com/package/evmexplorer": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/e/evm-explorer-pfed-prog.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/d/dspytdao.yaml"
  ],
  "https://www.npmjs.com/package/@evmexplorer/uniswap": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/e/evm-explorer-pfed-prog.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/d/dspytdao.yaml"
  ],
  "https://www.npmjs.com/package/@evmexplorer/blockscout": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/e/evm-explorer-pfed-prog.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/d/dspytdao.yaml"
  ],
  "https://www.npmjs.com/package/@evmexplorer/utility": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/e/evm-explorer-pfed-prog.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/d/dspytdao.yaml"
  ]
}
```

**Comment by Pfed-prog** [comment]
Ok, so my understanding is that npm packages should not be duplicated, what about github repos?

**Comment by Pfed-prog** [comment]
Any chance we could add more data on press release, news, testimonials in the schema?

**Comment by ccerv1** [comment]
> Ok, so my understanding is that npm packages should not be duplicated, what about github repos?

All artifacts can only be owned once -- no duplicates :)

**Review by ccerv1 — APPROVED** [review]
Let's try this now!

**Pull request merged**
