### PR TITLE
Update superfluid.yaml

### PR DESCRIPTION
**Pull request by mdalie**
Update the Superfluid project data entry with additional contract addresses on the Optimism and Base networks.

### CODE REVIEW

**Comment by ryscheng** [comment]
@mdalie Thank you for this!!

We are currently in the process of refactoring this directory to strongly bias towards just entering your `deployer` address, which we should be able to auto-detect your contracts deployed (either directly or indirectly via a factory).

Would you mind updating this by:
- Checking if your deployer address sufficiently covers all relevant contracts in our `contracts_v1` API?
https://cloud.hasura.io/public/graphiql?endpoint=https://opensource-observer.hasura.app/v1/graphql
- Then updating this file to only include deployer addresses?

**Review by ccerv1 — APPROVED** [review]
Thanks so much! These updates all look good. Will validate and merge ASAP. 🙌

**Comment by mdalie** [comment]
Awesome, thanks! I just want to make sure factory contracts are tracked correctly as most of Superfluid's activity is routed via contracts deployed by the listed factories (like SuperTokens, for example).

**Comment by ccerv1** [comment]
Validations passed 🎉 

We have a little bug in our validator that is attributing addresses that aren't in your project file to you, but I've manually reviewed and this is good to go!

Best of luck in RF4!

**Pull request merged**
