### PR TITLE
Add EntryPoint v0.7 and mark the version for EntryPoint v0.6

### PR DESCRIPTION
**Pull request by forshtat**

### CODE REVIEW

**Review by yoavw — APPROVED** [review]

**Comment by ccerv1** [comment]
Hi @yoavw and @forshtat 

I've commented on the related PR #350:

> our preference for contracts is to enumerate them individually rather than using the `any_evm` tag (we want to reserve `any_evm` for EOAs)

Therefore, my recommendation would be the following for your updated entry:

```
version: 7
name: eth-infinitism-account-abstraction
display_name: Infinitism (ERC-4337) - Account Abstraction
github:
  - url: https://github.com/eth-infinitism/account-abstraction
blockchain:
  - address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
    networks:
      - base
      - optimism
    tags:
      - contract
    name: EntryPoint (v0.6)
  - address: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
    networks:
      - base
      - optimism
    tags:
      - contract
    name: EntryPoint (v0.7)
  - address: "0x6a957e69a251d37cfd1f538f18ec1416fbdfa501"
    networks:
      - any_evm
    tags:
      - eoa
      - wallet
websites:
  - url: https://erc4337.io/
  - url: http://discord.gg/fbDyENb6Y9
description: An infinite game is not played for winning, but for continuing the
  play — James Carse, Finite & Infinite Games 1986
social:
  twitter:
    - url: https://twitter.com/erc4337 
```

If I don't hear back from you in a few hours, I am happy to push this change myself. Thank you again for your contributions!

**Comment by yoavw** [comment]
Thanks @ccerv1 !   Your suggestion makes sense, let's do that.  For OP stack we can add the smaller ones if they're supported, so it's optimism,base,zora,fraxtal,mode.  In the future we can add non-OP ones - there are quite a few.

**Comment by ccerv1** [comment]
> Thanks @ccerv1 ! Your suggestion makes sense, let's do that. For OP stack we can add the smaller ones if they're supported, so it's optimism,base,zora,fraxtal,mode. In the future we can add non-OP ones - there are quite a few.

Yes, thats fine! Just note that we call fraxtal `frax`

**Review by ccerv1 — APPROVED** [review]
Looks good! Approved and will validate now.

**Pull request merged**
