### PR TITLE
Update superfluid contracts 

### PR DESCRIPTION
**Pull request by mmd-afegbua**

### CODE REVIEW

**Comment by ravenac95** [comment]
Thanks for the update :)! At the moment we don't have any matic data and are still in progress determining a path for our arbitrum data. Let me discuss with the other guys what the best solution is here.

**Comment by mdalie** [comment]
We could remove these networks until later date, and push a PR to include those once they are supported 😉

**Comment by ccerv1** [comment]
> We could remove these networks until later date, and push a PR to include those once they are supported 😉

I believe the PR should still go through, assuming they are networks we've already enumerated. Check this now!

**Pull request merged**
