### PR TITLE
Adds loot2

### PR DESCRIPTION
**Pull request by mcgingras**
Let me know if this looks okay, thanks!

### CODE REVIEW

**Comment by ccerv1** [comment]
> Let me know if this looks okay, thanks!

Looks perfect! Running the validator to confirm.

**Comment by ccerv1** [comment]
> Let me know if this looks okay, thanks!

Spoke to soon. Indent error 😡

**Review by ccerv1 — APPROVED** [review]
Fixed the indents - let me validate now

**Comment by mcgingras** [comment]
whoops, sorry about that, thanks for the fix! Anything that I need to do?

**Comment by ccerv1** [comment]
All good, we've merged. TYSM

**Pull request merged**
