### PR TITLE
L1StandardBridge and L2StandardBridge for Superchain networks

### PR DESCRIPTION
**Pull request by AlexBHarley**
- [Base](https://docs.base.org/docs/base-contracts/#base-mainnet)
- [OP Mainnet](https://docs.optimism.io/chain/addresses#ethereum-l1)
- [Zora](https://docs.zora.co/docs/zora-network/network)
- [Mode](https://docs.mode.network/general-info/mainnet-contract-addresses/l1-l2-contracts)

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
Amazing! TYSM, @AlexBHarley 🎉

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Shoot! I just realized that this came in before our migration 😮‍💨 
Could you please rebase and ensure the project files all have version 7?
If I don't hear back from you in 24 hours, I will this manually for you.
Thanks again ser

**Comment by AlexBHarley** [comment]
@ccerv1 let me know if that's good to go!

**Comment by ccerv1** [comment]
hey @AlexBHarley here's my updated implementation of your additions. let me know if this looks OK to you and if you I will close out your PR. thanks again for your contribution and patience -- there were a few things we had to fix to get this to work 😅 

https://github.com/opensource-observer/oss-directory/pull/360

**Pull request closed without merging**
