### PR TITLE
add: new project The-book-of-optimism-fault-proof

### PR DESCRIPTION
**Pull request by joohhnnn**
Hi there Im not sure if there is a tag named fault proof. If not, PLZ delete it.

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Hi there, we have a separate project already for you here:
https://github.com/opensource-observer/oss-directory/blob/main/data/projects/u/understanding-optimism-codebase-joohhnnn.yaml

This gives you two options:
- Merge: Add the Github urls to that projects and update the name
- Separate: Keep a separate file for each project, but remove the address from the new one -- we can't have two projects "own" the same address

Both are totally fine... up to you!

**Comment by joohhnnn** [comment]
> Hi there, we have a separate project already for you here: https://github.com/opensource-observer/oss-directory/blob/main/data/projects/u/understanding-optimism-codebase-joohhnnn.yaml
> 
> This gives you two options:
> 
> * Merge: Add the Github urls to that projects and update the name
> * Separate: Keep a separate file for each project, but remove the address from the new one -- we can't have two projects "own" the same address
> 
> Both are totally fine... up to you!

Thanks for the advice. I use a new address for the Separate case. PLZ check again.

**Review by ccerv1 — APPROVED** [review]
Made some small labeling changes, should be good to go now

**Pull request merged**
