### PR TITLE
Contribute to 0x Project

### PR DESCRIPTION
**Pull request by wonge97**
Extend `.yaml` file with contract addresses for settlement contract on EVM chains. Addresses can be confirmed via docs here: https://0x.org/docs/developer-resources/contract-addresses

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
thanks for your PR! 
we realized that we already had `0xproject` contracts but they were misattributed to a project called "Zero Exchange". I have just [pushed a PR](https://github.com/opensource-observer/oss-directory/pull/321/files) that fixes this.
I diffed it against your PR and it includes the same contracts (as well as other contracts deployed by the same deployers).

Please have a look. If there are any further changes, please rebase to my version and submit. Otherwise, feel free to close your PR.

Thank you again!

**Comment by wonge97** [comment]
thanks @ccerv1 , I just pushed a small update to the social links but otherwise appreciate the re-attritbution.

**Comment by ccerv1** [comment]
> thanks @ccerv1 , I just pushed a small update to the social links but otherwise appreciate the re-attritbution.

Looks great! By the way, do you have any knowledge to the other "Zero Exchange" project? Do you know if it's even active?

**Comment by ccerv1** [comment]
@wonge97 I noticed that we had some self-destruct contracts in your entry previously. I've removed those. I *think* everything should be good now, but in order to merge these updates you will need to rebase your PR. If I don't hear back from you in 24 hours, I will do this manually. Thanks again!

**Comment by wonge97** [comment]
As for what addresses are there, this is what we list on our side: https://0x.org/docs/developer-resources/contract-addresses

**Comment by ccerv1** [comment]
OK - I've manually PRed your updates [here](https://github.com/opensource-observer/oss-directory/pull/339). We've had some issues with our validator that I'm trying to clear out, so this was quicker :)

Thanks again and love what you're building! Best of luck in RF4 🎉

**Pull request closed without merging**
