### PR TITLE
Create apriloracle.yaml

### PR DESCRIPTION
**Pull request by Apriloracle**
Adding our project .yaml file to the directory.

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
Looks good!

**Review by ccerv1 — APPROVED** [review]

**Comment by Apriloracle** [comment]
let me fix it

**Review by ccerv1 — APPROVED** [review]
Looks good, TY!

**Comment by ccerv1** [comment]
You included an [Axelar relayer address](https://optimistic.etherscan.io/address/0xd36aac0c9676e984d72823fb662ce94d3ab5e551), not a project deployer. 

It also appears that you uploaded your contract to GitHub <1 hour ago. 

I'm going to close this PR. Please review the Retro Funding eligibility requirements more closely before opening another PR. Thank you

**Comment by Apriloracle** [comment]
Yes we have been actually working with Axelar on this issue because the RetroGrant site is not able to verify their deployer signature. Axelar has been in touch with Optimism team as there are a few other projects like us in the same situation. That is why we are exploring this second option.

**Comment by benjamin852** [comment]
Hi confirming as well @blockchainguyy is from axelar team helping out with @Apriloracle with this matter.

**Pull request closed without merging**
