### PR TITLE
rebuild of OSS-D using only validated addresses

### PR DESCRIPTION
**Pull request by ccerv1**

### CODE REVIEW

**Comment by ravenac95** [comment]
@ccerv1 I uploaded all of these to a table `projects-test` in BigQuery. I compared it against what we currently have:

_For purpose of comparison an "Address" is the tuple of `Address + Network + Type of Address`_

* Total Addresses after change: 25746
    * Total Before change: 24997
* 18687 Unchanged Addresses
* This PR removes 6562 Addresses
* This PR adds 7311 Address + Network pairs
    * 2059 of these are arbitrum contracts we didn't pull data for on Dune and that represents ~36K transactions we didn't record
*

**Comment by ccerv1** [comment]
Thanks @ravenac95 !
Is it possible to get a difference in sequencer fees (pct change) relative to what they were previously? Without that diff it’s hard to put the absolute numbers in context. I’d like to know that before merging

**Comment by ravenac95** [comment]
Oh definitely! Let me run that query!

-Reuven

**Comment by ravenac95** [comment]
@ccerv1 

Results from that query: https://dune.com/queries/3424472?contracts_table_t6c1ea=574e8d8b18d8f4098f8

* L2 Gas Used (gwei): 19783318368224
* L1 Gas Used (gwei): 17078943374507
* # of transactions: 17926231 
    * (I messed up the previous number i realized). So it is a significant chunk. I was counting a heavily aggregated value.

**Pull request merged**
