### PR TITLE
adding farcards

### PR DESCRIPTION
**Pull request by beachCrypto**
adding the farcards project to OSS

### CODE REVIEW

**Comment by beachCrypto** [comment]
We are adding our addresses to be eligible for Retro Funding

**Review by ccerv1 — CHANGES_REQUESTED** [review]
hi there
please have a look at [the docs](https://docs.opensource.observer/docs/contribute/project-data#schema-overview) for making a project file
there are a few issues:
- version should be 7
- github url is missing
- addresses should include a deployer (or contract if you don't control the deployer)

**Comment by beachCrypto** [comment]
thank you @ccerv1 - I have updated the version and changed the address tags to deployer. Is a Github url required? Our project is using the mint.club sdk who we have been partnering with, which uses a Business Source License. Our intention is to open source data on Farcards

**Review by ccerv1 — APPROVED** [review]
I'm going to approve even without the github repo to see if your project passes eligibility requirements.

**Comment by ccerv1** [comment]
hi @beachCrypto -- we weren't able to find any qualifying contract deployments on base from the addresses you provided. If you believe this is a mistake, please provide a link to a valid `create` contract transaction (eg, on BaseScan) and we can try to update it last minute.

**Pull request closed without merging**
