### PR TITLE
Adding curio.yaml

### PR DESCRIPTION
**Pull request by snadrus**

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Hi @snadrus - thank you for your PR!
We already have Filecoin Project (and all its repos) captured in OSS Directory. To prevent a collision (ie, two projects trying to claim the same repo), we will need to break out the other relevant repos. I can do that through a separate PR, but just want to confirm that's the desired outcome.

**Comment by snadrus** [comment]
Simple: yes.
Precise:
Protocol Labs nucleated into over a dozen smaller companies. This concluded over 6 months ago. The filecoin-project is now an umbrella shared by cooperative companies. A company, FilOz, manages Lotus and a few more. IPNI is managed by someone else. Filecoin Foundation has a few more, as does Elliptic Reasearch. Protocol Labs (the original blanket owner) may know the comprehensive breakdown of company-->repos better than I do.

**Comment by ccerv1** [comment]
OK, I've made the change to filecoin-project! I am going to change your filename to `curio-filecoin-project` and then try to validate your PR

**Comment by ccerv1** [comment]
Merged here: https://github.com/opensource-observer/oss-directory/pull/550

**Pull request closed without merging**
