### PR TITLE
Add axelarnetwork

### PR DESCRIPTION
**Pull request by blockchainguyy**

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
thanks for your submission ser!

we currently don't have a validator for checking contracts on every chain that have the `any_evm` tag. instead, we have asked projects to enumerate the chains the contract is deployed on.

for example:

```
  - address: "0x2d5d7d31F671F86C782533cc367F14109a082712"
    networks:
      - any_evm
    tags:
      - contract
    name: AxelarGasServiceProxy
```

should be updated to ...

```
  - address: "0x2d5d7d31F671F86C782533cc367F14109a082712"
    networks:
      - arbitrum_one
      - base
      - mainnet  
      - optimism
    tags:
      - contract
    name: AxelarGasServiceProxy
```

in the future, we'll do a migration that will take care of this for you so you don't need to keep adding individual networks

**Comment by spaliwal-qodeleaf** [comment]
> - arbitrum_one
>       - base

@ccerv1 Have made the change.

**Review by ccerv1 — APPROVED** [review]
thanks!! this all looks good. we don't have live validators for frax, but we still grab the data once the contracts are approved. so you should be good to go. let me run the validator and confirm.

**Comment by ccerv1** [comment]
All validators passed, thanks so much!

**Pull request merged**
