### PR TITLE
Update Pairwise data

### PR DESCRIPTION
**Pull request by mmahdigh**

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
lgtm! thank you!

**Comment by ccerv1** [comment]
@mmahdigh do you want to submit this PR? It's still in draft mode

**Comment by mmahdigh** [comment]
> @mmahdigh do you want to submit this PR? It's still in draft mode

Hi! Thanks for approving it!

I'm waiting for some team members to approve the changes I have made. Will make it ready to merge once I get the greenlight from them.

**Comment by mmahdigh** [comment]
@ccerv1 please merge this if everything is okay on your side.

**Pull request merged**
