### PR TITLE
adding moxie

### PR DESCRIPTION
**Pull request by shnoodles**
Hi team,

Raising a new PR to add [Moxie Protocol](https://moxie.xyz/) and it's deployer addresses.

Please let me know if there are any issues or questions

Cheers,
Ignas

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
Looks good, thanks!

**Comment by shnoodles** [comment]
Hi @ccerv1 thank you!

**Comment by shnoodles** [comment]
Hi @ccerv1 I had a quick question - is there anything else pending on our side for the Moxie contracts to get indexed by OSO? Just trying to understand if I missed a step.

Appreciate the support.

**Comment by ccerv1** [comment]
> Hi @ccerv1 I had a quick question - is there anything else pending on our side for the Moxie contracts to get indexed by OSO? Just trying to understand if I missed a step.
> 
> Appreciate the support.

Hey @shnoodles 
Yep, I'm seeing 55K contracts deployed (on Base)! That sound about right to you?
image

**Comment by shnoodles** [comment]
Hi @ccerv1 sorry for delayed response. Yes, sounds about right (approx).

We have deployed 53k+ TokenLockWallets to manage our Airdrops - those vesting contracts allow users to participate in the protocol with the vesting tokens, while they are vesting.

**Pull request merged**
