### PR TITLE
Create poster.yaml

### PR DESCRIPTION
**Pull request by thearyanag**

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Hi there, please review our schema [docs](http://github.com/lenspost-labs) and fix:

- version: 7
- filename / project_name should be the same as your github org
- provide the deployer address and the `any_evm` tag instead of listing all your contracts

**Comment by thearyanag** [comment]
hey @ccerv1 , we don't have a single deployer address, as we create custodial wallets for user, then user fund those wallets and we use those wallets for contract deployments, how should we go about it then?

**Review by ccerv1 — APPROVED** [review]
Per feedback, going to try the validator on this PR.

**Review by ccerv1 — COMMENTED** [review]
We already had a project file for `lenspost-labs`. I'm adding your PR manually. You can follow here: https://github.com/opensource-observer/oss-directory/pull/380/commits/c687aad287fbad40c605ec6a2b0a52169a4e842f

**Comment by thearyanag** [comment]
thanks @ccerv1

**Pull request closed without merging**
