### PR TITLE
Socket details fix

### PR DESCRIPTION
**Pull request by arthcp**
This PR updates the details about socket.
- new npm packages
- fix links and description
- latest contract and deployer addresses

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
Thanks! This is a huge list 😅  

One feature that's available is to just include the deployers and add the `any_evm` network. then we automatically grab any contract downstream from it (including factories that deploy additional contracts) as well contracts created via a create2.

Anyway, let me try validating what you have. If it throws an error, we might want to consider this option, provided your project deployers haven't been used anywhere else.

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Sorry, there's an indentation issue in the YAML that prevented it from being validated. I believe you need to add spaces before the `networks` field for the new entries you added. 

image

(see line 686 -- it should be lined up with the indent in line 680)

**Comment by arthcp** [comment]
Fixed the indentation issue.

I guessed the older list was generated using deployer addresses. But we do discard deployed contracts a lot of time so if had a lot of noise.

**Review by ccerv1 — APPROVED** [review]
Thanks!! Going to run the validator now.

**Comment by ccerv1** [comment]
All good! Merging. Thank you!!

**Pull request merged**
