### PR TITLE
Create castnotes.yaml

### PR DESCRIPTION
**Pull request by NetWalker108**
Adding CastNotes to the OSO.

### CODE REVIEW

**Review by ccerv1 — APPROVED** [review]
@NetWalker108 thanks for your PR! I extended the scope to the full GitHub org space, not just the main repo. That way, as the project evolves, we can continue to index everything. This is how we handle >90% of projects. If you'd prefer to keep it confined to just the one repo, then let me know. Thx

**Comment by NetWalker108** [comment]
Hey @ccerv1, thanks so much for this. Still new to OSO so will definitely go for the default recommended option.

**Review by ccerv1 — CHANGES_REQUESTED** [review]
Ah whoops, do you have a contract or deployer address on base?
Here's an example of how to get the address in there and tag it.
https://docs.opensource.observer/docs/how-oso-works/oss-directory/project#example

**Review by ccerv1 — APPROVED** [review]
@NetWalker108 OK, I've removed your blockchain entry -- we can still merge your PR to get your project on OSO and then when you have contracts or other addresses you want to link, we can do that later. Keep buidling!

**Pull request merged**
