### PR TITLE
Add CMT

### PR DESCRIPTION
**Pull request by akshatmittal**
Adds CreateMyToken to the list of protocols. The list of contracts is partial, and is the most recent revision.

Question: All contracts are deployed using Multicall + Create2 Factory. In our case, the both the contracts themselves and it's proxies are deployed by the user themselves. All platform interactions as well, including Liquidity and Token Management happen via Multicall as well (we use it as a Batcher for the user). And direct interactions happen via a user-specific proxy. Would the Observer track internal transactions appropriately? (Alternatively, I can add the Multicall and Create2 Factory to the list of addresses, just let me know!)

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
hi there, please make sure to apply the correct networks and tags for your blockchain addresses. if you are using the `any_evm` network, then we are typically expecting a `deployer` and `eoa` tag, not a `contract`. For more info, please see the docs [here](https://docs.opensource.observer/docs/contribute/project-data#supported-blockchain-networks-and-tags)

**Comment by akshatmittal** [comment]
@ccerv1 So, these contracts are deployed across chains using a deterministic deploy method, however they are deployed by the user themselves so not a specific deployer address. It's a very specific case for sure, so I'm happy to provide info as necessary.

**Comment by ccerv1** [comment]
> Adds CreateMyToken to the list of protocols. The list of contracts is partial, and is the most recent revision.
> 
> Question: All contracts are deployed using Multicall + Create2 Factory. In our case, the both the contracts themselves and it's proxies are deployed by the user themselves. All platform interactions as well, including Liquidity and Token Management happen via Multicall as well (we use it as a Batcher for the user). And direct interactions happen via a user-specific proxy. Would the Observer track internal transactions appropriately? (Alternatively, I can add the Multicall and Create2 Factory to the list of addresses, just let me know!)

Ahh! Just seeing your comment. I manually checked a few of the contracts, and now I understand why you did it this way. 

Let me take a closer look tomorrow on how best to handle your case!

**Comment by ccerv1** [comment]
> @ccerv1 So, these contracts are deployed across chains using a deterministic deploy method, however they are deployed by the user themselves so not a specific deployer address. It's a very specific case for sure, so I'm happy to provide info as necessary.

Got it! Let me investigate with a clear head tomorrow :) 
Feel free to link an example of tx hash involving one of your contracts on OP or Base. 
Cheers :)

**Comment by akshatmittal** [comment]
> Let me take a closer look tomorrow on how best to handle your case!

Thank you very much. I've only included a bare minimum contracts here from the latest revision, maybe I can also add the Create2 Deployer with the "deployer" (?) tag to include contracts deployed via Create2.

Example TX that includes base contract deployment + proxy: https://basescan.org/tx/0x5328e042d72f2ca9569249d1197ee300ea889ff0ccb25332a56de801efeb562f
Example TX that includes proxy deployment + liquidity creation (batcher): https://basescan.org/tx/0xc6ffb689b2ade6ca42f8264500c007da1bb2e808d26aa4772b48fd679d5b7641

**Comment by ccerv1** [comment]
> Hey @ccerv1, just checking in. The primary question I need to answer right now if I need to include the Create2 Factory and/or the Multicall batching contract into this list. Probably need to have this be included today to be able to submit the application in time. Thanks for looking into it! :)

Let me check for you now ...

**Review by ccerv1 — APPROVED** [review]

**Comment by ccerv1** [comment]
Hi @akshatmittal 
It looks like 5/7 contracts were accepted. 2/7 didn't meet the validation. 

- 0xc710077cee595e3e0745c3bb117c5c7793e52731
- 0x781d963b5c94590a324a6300d9ada11caedf7260

I might also suggest adding your create2 and multicall addresses (or, alternatively, the deployer that interacted with these).

If you do that, please rebase you pull request. There are some addresses associated with a project that got erroneously merged before you forked oss-directory. The problem should resolve if you rebase, add/fix the points above, and submit again.

Thank you!

**Comment by akshatmittal** [comment]
> 2/7 didn't meet the validation.

@ccerv1 Can you clarify why they weren't validated? Both of them are deployed on Base, so should be detected.

And yeah, let me add the create2 factory and the multicall address to this list.

**Comment by ccerv1** [comment]
> > 2/7 didn't meet the validation.
> 
> @ccerv1 Can you clarify why they weren't validated? Both of them are deployed on Base, so should be detected.
> 
> And yeah, let me add the create2 factory and the multicall address to this list.

Thanks! Those two are still failing. I'm checking to see if it works by specifying that we only care about Base.

**Comment by akshatmittal** [comment]
> I'm checking to see if it works by specifying that we only care about Base.

Okay yeah. Just to clarify, they are both deployed on ~8 networks at the moment and by the end of this week they will be enabled/available on the entire Superchain ecosystem instead of just Base/OP, so ideally would like to use `any_evm`.

**Comment by ccerv1** [comment]
> > I'm checking to see if it works by specifying that we only care about Base.
> 
> Okay yeah. Just to clarify, they are both deployed on ~8 networks at the moment and by the end of this week they will be enabled/available on the entire Superchain ecosystem instead of just Base/OP, so ideally would like to use `any_evm`.
> 
> Edit: I see that validation passes with just `base` so I guess the validator is still giving troubles haha

Yes! I was trying to figure out what was going on with it. In any case, I recommend merging this now. Optimism is taking a snapshot of activity so even if these contracts have a lot of activity on other chains in the next few days it won't be relevant to the retro funding round :(

Regardless, I will create an issue to chase this down and update your project file accordingly.

Thanks for your patience -- and very cool project too 🚀

**Comment by akshatmittal** [comment]
> Thanks for your patience -- and very cool project too 🚀

Thanks for bearing with me @ccerv1, I understand this is a unique situation! Appreciate the kind words as well!

**Comment by akshatmittal** [comment]
Hey @ccerv1, quick question, when can I expect CreateMyToken to show up on Opensource Observer? (I'm expecting discovery on the factory to find a couple thousand tokens, so I'm myself interested in looking at the combined stats for them!)

**Pull request merged**
