### PR TITLE
Add zkcodex.yaml

### PR DESCRIPTION
**Pull request by yusufky63**

### CODE REVIEW

**Review by ccerv1 — CHANGES_REQUESTED** [review]
This project does not have any public GitHub repositories. If you are applying for Retro Funding, then it will not pass the eligibility criteria.

image

**Comment by yusufky63** [comment]
Added

**Review by ccerv1 — APPROVED** [review]
Looks good now, thank you!

**Comment by ccerv1** [comment]
Your PR passes validations and I'm merging it. Make sure you complete your application on Retro Funding and include these contracts.

**Pull request merged**
